{{- if .Values.agentbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.agentbox.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: agentbox
type: Opaque
data:
  {{- include "dify.agentbox.credentials" . | nindent 2 }}
{{- end }}
