{{- if .Values.agentBackend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.agentBackend.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: agent-backend
type: Opaque
data:
  {{- include "dify.agentBackend.credentials" . | nindent 2 }}
{{- end }}
