{{- if and .Values.externalSecret.enabled .Values.externalSecret.agentBackend.enabled .Values.agentBackend.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "dify.agentBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-backend
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ template "dify.agentBackend.fullname" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- if .Values.externalSecret.agentBackend.data.DIFY_AGENT_REDIS_URL }}
        DIFY_AGENT_REDIS_URL: {{ .Values.externalSecret.agentBackend.data.DIFY_AGENT_REDIS_URL }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN }}
        DIFY_AGENT_API_TOKEN: "{{ `{{ .DIFY_AGENT_API_TOKEN }}` }}"
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY }}
        DIFY_AGENT_SERVER_SECRET_KEY: "{{ `{{ .DIFY_AGENT_SERVER_SECRET_KEY }}` }}"
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN }}
        DIFY_AGENT_SHELLCTL_AUTH_TOKEN: "{{ `{{ .DIFY_AGENT_SHELLCTL_AUTH_TOKEN }}` }}"
        {{- end }}
        {{- if and .Values.pluginDaemon.enabled .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY }}
        DIFY_AGENT_PLUGIN_DAEMON_API_KEY: "{{ `{{ .DIFY_AGENT_PLUGIN_DAEMON_API_KEY }}` }}"
        {{- end }}
        {{- if and .Values.pluginDaemon.enabled .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY }}
        DIFY_AGENT_INNER_API_KEY: "{{ `{{ .DIFY_AGENT_INNER_API_KEY }}` }}"
        {{- end }}
  data:
    {{- if .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD }}
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.REDIS_PASSWORD.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN }}
    - secretKey: DIFY_AGENT_API_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_API_TOKEN.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY }}
    - secretKey: DIFY_AGENT_SERVER_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SERVER_SECRET_KEY.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN }}
    - secretKey: DIFY_AGENT_SHELLCTL_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_SHELLCTL_AUTH_TOKEN.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- if and .Values.pluginDaemon.enabled .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY }}
    - secretKey: DIFY_AGENT_PLUGIN_DAEMON_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_PLUGIN_DAEMON_API_KEY.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- if and .Values.pluginDaemon.enabled .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY }}
    - secretKey: DIFY_AGENT_INNER_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY.key }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY.property }}
        property: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY.property }}
        {{- end }}
        {{- if .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.agentBackend.remoteRefs.DIFY_AGENT_INNER_API_KEY.decodingStrategy }}
        {{- else if .Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
{{- end }}
