{{- if and .Values.api.enabled}}
{{- $usePvc := not (or .Values.externalS3.enabled .Values.externalAzureBlobStorage.enabled .Values.externalOSS.enabled .Values.externalGCS.enabled .Values.externalCOS.enabled .Values.externalOBS.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "dify.ud.annotations" . | indent 4 }}
    descriptions: api
  labels:
{{- include "dify.labels" . | nindent 4 }}
    component: api
    # app: {{ template "dify.api.fullname" . }}
{{ include "dify.ud.labels" . | indent 4 }}
  name: {{ template "dify.api.fullname" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{- include "dify.selectorLabels" . | nindent 6 }}
      component: api
      {{/*
      # Required labels for istio
      # app: {{ template "dify.api.fullname" . }}
      # version: {{ .Values.istioServiceMesh.version | quote }}
      */}}
  {{- if .Values.api.updateStrategy }}
  strategy: {{- toYaml .Values.api.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/api-config: {{ include (print $.Template.BasePath "/api-config.yaml") . | sha256sum }}
        checksum/api-secret: {{ include (print $.Template.BasePath "/api-secret.yaml") . | sha256sum }}
{{ include "dify.ud.annotations" . | indent 8 }}
      labels:
{{- include "dify.selectorLabels" . | nindent 8 }}
        component: api
        {{/*
        # Required labels for istio
        # app: {{ template "dify.api.fullname" . }}
        # version: {{ .Values.istioServiceMesh.version | quote }}
        */}}
{{ include "dify.ud.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "dify.api.serviceAccountName" . }}
      {{- if .Values.api.priorityClassName }}
      priorityClassName: {{ .Values.api.priorityClassName | quote }}
      {{- end }}
      {{- if eq .Release.Name "dify"}}
      {{/*
      Disable service environment variables,
      otherwise they will clash with `DIFY_PORT` which is needed in entrypoint.sh
      */}}
      enableServiceLinks: false
      {{- end }}
      {{- if .Values.image.api.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.api.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.api.podSecurityContext }}
      securityContext:
{{ toYaml .Values.api.podSecurityContext | indent 8 }}
      {{- end }}
      initContainers:
        - name: check-postgres
          image: "{{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          command:
            - sh
            - -c
            - |
              until PGPASSWORD=$DB_PASSWORD pg_isready -h $DB_HOST -U $DB_USERNAME -d $DB_DATABASE ; do
                echo "Waiting for PostgreSQL sequence to be available..."
                sleep 1
              done
              echo "PostgreSQL is ready."
          envFrom:
          - configMapRef:
              name: {{ template "dify.api.fullname" . }}
          - secretRef:
              name: {{ template "dify.api.fullname" . }}
        - name: check-redis
          image: "{{ .Values.redis.image.registry }}/{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          command:
            - sh
            - -c
            - |
              until redis-cli -h $REDIS_HOST -p $REDIS_PORT -a $REDIS_PASSWORD ping | grep -q PONG; do
                echo "Waiting for Redis service to be available..."
                sleep 1
              done
              echo "Redis is ready."
          envFrom:
          - configMapRef:
              name: {{ template "dify.api.fullname" . }}
          - secretRef:
              name: {{ template "dify.api.fullname" . }}
      containers:
      - image: "{{ .Values.image.api.repository }}:{{ default .Chart.AppVersion .Values.image.api.tag }}"
        imagePullPolicy: "{{ .Values.image.api.pullPolicy }}"
        name: api
        {{- if .Values.api.customLivenessProbe }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customLivenessProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.livenessProbe.enabled }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.livenessProbe "enabled") "context" $) | nindent 10 }}
          httpGet:
            path: /health
            port: api
        {{- end }}
        {{- if .Values.api.customReadinessProbe }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customReadinessProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.readinessProbe.enabled }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.readinessProbe "enabled") "context" $) | nindent 10 }}
          httpGet:
            path: /health
            port: api
        {{- end }}
        {{- if .Values.api.customStartupProbe }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customStartupProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.startupProbe.enabled }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.startupProbe "enabled") "context" $) | nindent 10 }}
          tcpSocket:
            port: api
        {{- end }}
        {{- if .Values.api.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.api.containerSecurityContext | indent 10 }}
        {{- end }}
        env:
        {{- if .Values.sandbox.enabled }}
        - name: CODE_EXECUTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "dify.sandbox.fullname" . }}
              key: "API_KEY"
        {{- end }}
        {{- if .Values.api.extraEnv }}
          {{- toYaml .Values.api.extraEnv | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "dify.api.fullname" . }}
        - secretRef:
            name: {{ template "dify.api.fullname" . }}
        ports:
          - name: api
            containerPort: 5001
            protocol: TCP
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        volumeMounts:
        {{- if $usePvc }}
        - name: app-data
          mountPath: {{ .Values.api.persistence.mountPath | quote }}
          subPath: {{ .Values.api.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}
    {{- if and (.Values.nodeSelector) (not .Values.api.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.api.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.affinity) (not .Values.api.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.api.affinity }}
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.api.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.api.tolerations }}
      tolerations:
{{ toYaml .Values.api.tolerations | indent 8 }}
    {{- end }}
      volumes:
      {{- if $usePvc }}
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ .Values.api.persistence.persistentVolumeClaim.existingClaim | default (printf "%s" (include "dify.fullname" . | trunc 58)) }}
      {{- end }}
{{- end }}
