{{- if .Values.beat.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dify.beat.serviceAccountName" . }}
  labels: {{- include "dify.labels" . | nindent 4 }}
    component: beat
  {{- if or .Values.beat.serviceAccount.annotations (include "dify.ud.annotations" .) }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.beat.serviceAccount.annotations (include "dify.ud.annotations" .) ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.beat.serviceAccount.automountServiceAccountToken }}
{{- end }}
