{{- if and .Values.externalE2bSandbox.enabled .Values.externalE2bSandbox.tls.enabled (not .Values.externalE2bSandbox.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-e2b-tls" (include "dify.fullname" .) }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: agent-backend
type: Opaque
data:
  {{ .Values.externalE2bSandbox.tls.certCAFilename }}: {{ .Values.externalE2bSandbox.tls.ca | b64enc | quote }}
{{- end }}
