{{- if .Values.httproute.enabled -}}
{{- $route := .Values.httproute -}}
apiVersion: {{ $route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: HTTPRoute
metadata:
  name: {{ template "dify.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- with $route.additionalRules }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- if .Values.proxy.enabled }}
    - backendRefs:
        - name: {{ include "dify.fullname" . }}
          port: {{ .Values.service.port }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else }}
    {{- if .Values.api.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /console/api
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /v1
        - path:
            type: PathPrefix
            value: /files
        - path:
            type: PathPrefix
            value: /openapi
        - path:
            type: PathPrefix
            value: /mcp
        - path:
            type: PathPrefix
            value: /triggers
      backendRefs:
        - name: {{ include "dify.api.fullname" . }}
          port: {{ .Values.api.service.port }}
    {{- end }}
    {{- if .Values.pluginDaemon.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /e/
      backendRefs:
        - name: {{ include "dify.pluginDaemon.fullname" . }}
          port: {{ .Values.pluginDaemon.service.ports.daemon }}
    {{- end }}
    {{- if .Values.apiWebsocket.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: {{ include "dify.apiWebsocket.fullname" . }}
          port: {{ .Values.apiWebsocket.service.port }}
    {{- end }}
    {{- if and .Values.externalE2bSandbox.enabled .Values.agentBackend.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /agent-stub
      backendRefs:
        - name: {{ include "dify.agentBackend.fullname" . }}
          port: {{ .Values.agentBackend.service.port }}
    {{- end }}
    {{- if .Values.web.enabled }}
    - backendRefs:
        - name: {{ include "dify.web.fullname" . }}
          port: {{ .Values.web.service.port }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end -}}
