{{- if and .Values.localSandbox.enabled (not (and .Values.externalSecret.enabled .Values.externalSecret.localSandbox.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.localSandbox.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: local-sandbox
type: Opaque
data:
  {{- include "dify.localSandbox.credentials" . | nindent 2 }}
{{- end }}
