{{- if and .Values.externalSecret.enabled .Values.externalSecret.postgresql.enabled .Values.postgresql.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgresql.global.postgresql.auth.existingSecret | default (printf "%s-postgresql" (include "dify.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  refreshInterval: {{ .Values.externalSecret.postgresql.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.postgresql.global.postgresql.auth.existingSecret | default (printf "%s-postgresql" (include "dify.fullname" .)) }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- if index .Values.externalSecret.postgresql.remoteRefs "postgres-password" }}
        postgres-password: "{{ `{{ index . \"postgres-password\" }}` }}"
        {{- end }}
        {{- if index .Values.externalSecret.postgresql.remoteRefs "replication-password" }}
        replication-password: "{{ `{{ index . \"replication-password\" }}` }}"
        {{- end }}
  data:
    {{- if .Values.externalSecret.postgresql.remoteRefs }}
    {{- range $secretKey, $remoteRef := .Values.externalSecret.postgresql.remoteRefs }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $remoteRef.key }}
        {{- if $remoteRef.property }}
        property: {{ $remoteRef.property }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
