# Azure AKS 환경을 위한 Dify 설정
# 이 파일은 Azure 클라우드 서비스와 통합하여 프로덕션 환경에서 사용하기 위한 설정입니다.
#
# 사용법:
# helm install dify ./charts/dify -f charts/dify/values-azure.yaml

# =============================================================================
# Azure 특화 설정
# =============================================================================

# 외부 PostgreSQL 사용 (Azure Database for PostgreSQL)
externalPostgres:
  enabled: true
  # Azure Database for PostgreSQL 엔드포인트 예시
  address: "dify-postgres.postgres.database.azure.com"
  port: 5432
  username: "dify_admin"
  # Azure Key Vault 또는 Kubernetes Secret 사용 권장
  password: "your-secure-password"
  database:
    api: "dify"
    pluginDaemon: "dify_plugin"

# 외부 Redis 사용 (Azure Cache for Redis)
externalRedis:
  enabled: true
  # Azure Cache for Redis 엔드포인트 예시
  host: "dify-redis.redis.cache.windows.net"
  port: 6380  # Azure Redis는 기본적으로 SSL 포트 사용
  username: ""
  # Azure Key Vault 또는 Kubernetes Secret 사용 권장
  password: "your-redis-primary-key"
  useSSL: true  # Azure Redis는 SSL 필수

# Azure Blob Storage 사용
externalAzureBlobStorage:
  enabled: true
  # Azure Storage Account 엔드포인트 예시
  url: "https://difystorage.blob.core.windows.net"
  account: "difystorage"
  # Azure Key Vault 또는 Kubernetes Secret 사용 권장
  key: "your-storage-account-key"
  container: "dify-storage"

# 내장 PostgreSQL 비활성화 (Azure Database 사용)
postgresql:
  enabled: false

# 내장 Redis 비활성화 (Azure Cache 사용)
redis:
  enabled: false

# 내장 Weaviate 사용 (또는 외부 벡터 DB 설정)
weaviate:
  enabled: true
  storage:
    size: 50Gi
    storageClassName: "managed-premium"  # Azure Premium SSD
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

# =============================================================================
# 인그레스 설정 (Azure Application Gateway Ingress Controller)
# =============================================================================

ingress:
  enabled: true
  className: "azure/application-gateway"
  annotations:
    # Azure Application Gateway Ingress Controller 설정
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/request-timeout: "300"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
    appgw.ingress.kubernetes.io/health-probe-interval: "30"
    appgw.ingress.kubernetes.io/health-probe-timeout: "5"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "3"
  hosts:
    - host: dify.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dify-tls
      hosts:
        - dify.yourdomain.com

# =============================================================================
# 스토리지 클래스 설정 (Azure Disk)
# =============================================================================

# API 컴포넌트 설정
api:
  enabled: true
  replicas: 2
  
  # 자동 스케일링 설정
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # 리소스 설정
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  # PVC 비활성화 (Azure Blob Storage 사용)
  persistence:
    enabled: false

  # 환경 변수
  extraEnv:
    - name: CHECK_UPDATE_URL
      value: "https://updates.dify.ai"  # Azure 환경에서는 활성화
    - name: CODE_MAX_NUMBER
      value: "9223372036854775807"
    - name: CODE_MIN_NUMBER
      value: "-9223372036854775808"
    - name: CODE_MAX_STRING_LENGTH
      value: "80000"

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux
    agentpool: systempool  # Azure AKS 시스템 노드풀

# Worker 컴포넌트 설정
worker:
  enabled: true
  replicas: 2
  
  # 자동 스케일링 설정
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 15
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # 리소스 설정 (백그라운드 작업용으로 더 많은 리소스)
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux
    agentpool: workerpool  # Azure AKS 작업자 노드풀

# Web 컴포넌트 설정
web:
  enabled: true
  replicas: 2
  
  # 자동 스케일링 설정
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  # 리소스 설정
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux

# Sandbox 컴포넌트 설정
sandbox:
  enabled: true
  replicas: 2
  
  # 리소스 설정
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux

# Plugin Daemon 설정
pluginDaemon:
  enabled: true
  replicas: 1
  
  # 리소스 설정
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # PVC 비활성화 (Azure Blob Storage 사용)
  persistence:
    enabled: false

  # 마켓플레이스 설정
  marketplace:
    enabled: true
    apiProxyEnabled: true  # Azure에서는 프록시를 통한 API 호출 사용

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux

# Proxy 설정
proxy:
  enabled: true
  replicas: 2
  
  # 리소스 설정
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

  # 로그 저장용 Azure Disk
  log:
    persistence:
      enabled: true
      storageClass: "managed-premium"
      size: 10Gi

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux

# SSRF Proxy 설정 (Azure 환경에서는 활성화 권장)
ssrfProxy:
  enabled: true
  replicas: 1
  
  # 리소스 설정
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

  # 로그 저장용 Azure Disk
  log:
    persistence:
      enabled: true
      storageClass: "managed-premium"
      size: 5Gi

  # Azure 특화 설정
  nodeSelector:
    kubernetes.io/os: linux

# =============================================================================
# 글로벌 설정
# =============================================================================

# Azure Availability Zones 지원
nodeSelector:
  kubernetes.io/os: linux

tolerations:
  # Azure Spot 인스턴스 사용 시 설정 예시
  # - key: "kubernetes.azure.com/scalesetpriority"
  #   operator: "Equal"
  #   value: "spot"
  #   effect: "NoSchedule"

affinity:
  # 멀티 가용 영역 배포를 위한 Anti-affinity 설정
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - dify
        topologyKey: topology.kubernetes.io/zone
    # Azure의 경우 Fault Domain도 고려
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - dify
        topologyKey: failure-domain.beta.kubernetes.io/zone

# 서비스 설정
service:
  type: ClusterIP  # Application Gateway를 통해 노출하므로 ClusterIP 사용
  port: 80
  annotations:
    # Azure Load Balancer 설정 (필요 시)
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "your-resource-group"

# 리소스 기본값 (개별 컴포넌트에서 오버라이드)
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# =============================================================================
# Azure 특화 모니터링 및 로깅
# =============================================================================

# Azure Container Insights와 통합을 위한 라벨
commonLabels:
  azure.workload.identity/use: "true"  # Azure Workload Identity 사용 시

# Azure 환경 변수 (필요 시)
# 모든 컴포넌트에 적용될 공통 환경 변수
extraEnv:
  - name: AZURE_CLIENT_ID
    value: "your-client-id"  # Azure Service Principal 사용 시
  - name: AZURE_TENANT_ID
    value: "your-tenant-id"
  # Azure Key Vault 사용 시
  # - name: AZURE_KEY_VAULT_URL
  #   value: "https://your-keyvault.vault.azure.net/"