dependencies:
- name: postgresql
  version: 12.5.6
  # repository: oci://registry-1.docker.io/bitnamicharts/postgresql
  repository: https://charts.bitnami.com/bitnami
  condition: postgres.enabled
  tags:
    - postgres